dist: focal
language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    packages:
      - build-essential
      - cmake
      - libboost-all-dev
      - libopencv-dev

script:
  - diff <(ls -l src | grep -i hpp | wc -l) <(git grep "namespace WayoutPlayer {" -- src | grep -i hpp | wc -l)
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - clang-tidy ../src/*
  - make
  - ./test
