dist: bionic
language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - build-essential
      - cmake
      - libboost-all-dev
      - libopencv-dev

script: mkdir build && cd build && cmake .. && make && ./test
