dist: bionic
language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - build-essential
      - cmake
      - libboost-all-dev
      - libopencv-dev

before_install:
  - sudo apt-get update
  - sudo apt-get install clang gcc --only-upgrade

script: mkdir build && cd build && cmake .. && make && ./test
